import FooterHeader from "./Components/FooterHeader";

export default function TermsConditions() {
    return (
        <>
            <div
                className='bg-white'
            >
                <div className=' text-center bg-[#FFF5F3] p-12'>
                    <h1 className="font-medium text-4xl sm:text-4xl md:text-5xl text-[#ff0000]">Terms and Conditions</h1>
                    {/* <p>We are dedicated to bridging the gap between talent and opportunity</p> */}
                </div>

                <div className=" p-12 space-y-4 max-w-7xl mx-auto text-justify">
                    <div>
                        <p className="text-2xl font-bold">Terms of Service for Job Seekers</p>
                        <p>For purposes of the Veritas Kenya Workforce Database (VeritasKWD/Veritas Jobs) Terms of Service, all references to “you” or “your” shall mean you, the individual or organization accessing this Site in your capacity as a Job Seeker. As a Job Seeker, you are permitted to use VeritasKWD Site and its content solely for non-commercial purposes.</p>

                        <dl>
                            <li>
                                <strong>Job Posts, Ads or Job Listings</strong>
                                <p>VeritasKWD may make available Job Ads advertising employment opportunities and other job-related content, including links to third-party websites (“Job Listings” or “Job Ads”), through the Site’s search results or otherwise through the Site. Searching for Job Ads on the Site is free for subscribers. The Site displays Jobs posted by employers to VeritasKWD. Relevance is based on search terms, other information provided, and activities conducted on the Site. While VeritasKWD may in some circumstances be compensated by employers who post Job Ads, helping keep VeritasKWD job search free for subscribed Job Seekers, all Job Ads are considered advertising.</p>
                                <p>Job Ads are created and provided by third parties over whom VeritasKWD exercises no control; you acknowledge and understand that VeritasKWD has no control over the content of Job Ads, links to or from Job Ads, or any conditions third parties might impose once a Job Seeker has submitted an application or left the Site. For example, some of these third parties may attempt to charge Job Seekers a fee to apply to a particular job, although VeritasKWD endeavors not to make such Job Ads available on the Site. If you leave the VeritasKWD Site and choose to enter a third-party website, you accept any terms and conditions imposed by that third-party. We cannot confirm the accuracy or completeness of any Job Ad or other information submitted by any Employer or other user, including the identity of such Employer or other user. VeritasKWD assumes no responsibility, and disclaims all liability for the content, accuracy, completeness, legality, reliability, or availability of any Job Ads, or other information submitted by any Employer or other user.</p>
                                <p>When you initiate a job application on a website operated by an Employer or its applicant tracking system, VeritasKWD may collect certain information about you and any actions taken by you during your visit using automated means, such as via Application Programming Interfaces (API), cookies, pixels, and web beacons. The information collected includes, for example, information about job listings you viewed and job applications you started and completed. An Employer who uses tracker functionality is required under this Agreement to provide any notice, and obtain any prior consent, that may be required by applicable law. However, you acknowledge and agree that VeritasKWD has no control over such an Employer or its website. You agree to VeritasKWD’s use of, and receipt of information from, any such tracker functionality.</p>
                                <p>VeritasKWD may provide independent functionality to assist you. For example, VeritasKWD may provide search options to help you narrow down Job Ads search results by job type categories (i.e. full-time, part-time, etc.), and such categories are created independently and entirely by VeritasKWD and may not directly or accurately reflect the content of the Job Ads. VeritasKWD may reformat Job Listings so that you may read them more clearly on a mobile phone. VeritasKWD does not guarantee that applying to jobs through a dedicated page or website will lead to a better job application experience, a job interview, or a job offer. The dedicated pages or website do not contain an exhaustive list of Job Ads, and no inferences can be drawn with respect to Job Ads or Employers that are not displayed on dedicated pages. VeritasKWD may also provide functionality to call a telephone number contained in a Job Ad using the phone app on a mobile device. VeritasKWD cannot guarantee that the extracted phone number is the correct phone number for the Employer or for the Job Ad you are viewing.</p>
                            </li>

                            <li>
                                <strong>Resume, Coursework and Profile</strong>
                                <p>By creating or adding information to a profile through the Site or uploading a file resume and coursework on the Site (collectively, “Your Profile” or “Job Seeker Profile” or “VeritasKWD Profile”), you are requesting and authorizing VeritasKWD to make available Your VeritasKWD Profile to anyone accessing our Site, such as Employers that VeritasKWD believes may have an interest in Your Profile, users of VeritasKWD’s Resume Search Program or Smart Sourcing, or anyone with access to the URL associated with your searchable Profile. We offer you the option to make Your Profile searchable on the Site to help you find a job. You are responsible for keeping Your Profile accurate and up to date.
                                    By creating or adding information or a resume to Your Profile, you are requesting and authorizing VeritasKWD, or  a VeritasKWD vendor, to review or scan Your Profile and resume(s) and provide you feedback (at VeritasKWD’s discretion), including suggested changes, other jobs you may consider applying to because your qualifications may match their requirements, and suggestions for additional information you may want to include with your application to a particular job. We may also provide you with feedback through additional resume review services, such as helping you understand how your resume or profile may be parsed by applicant tracking system software, feedback on ways to build a more effective resume or profile, or a personalized resume review video. We provide this feedback directly to you and may give you the ability to access it within your account. It is not made available to Employers. You agree that your use of any feedback or other information provided through resume and Coursework review services is at your sole discretion. You are the only one responsible for deciding which jobs to apply to and what to include in your applications. VeritasKWD assumes no responsibility and disclaims all liability for any actions you take based on any provided feedback. VeritasKWD does not guarantee that any recommended jobs are suited for you.
                                </p>
                                <p>By creating or adding information to a VeritasKWD Profile or uploading a file resume and coursework on the Site, VeritasKWD may share with you Job Ads that match the contents of Your Profile. VeritasKWD may also highlight to you items in Your Profile that may match qualifications from the Job Ad, or highlight to you items that appear in the Job Ad and may be missing from Your Profile. These highlights do not mean you are or are not qualified for the job or that you should or should not apply for it. Applying for such Job Ads does not guarantee job interviews or hiring. Even where VeritasKWD highlights items or a Job Ad is shared with you, VeritasKWD assumes no responsibility, and disclaims all liability for the content, accuracy, completeness, legality, reliability, or availability of Job Ads or highlights. By uploading a file resume and coursework on the Site, you agree that VeritasKWD may convert your file resume to a different file type. It is your responsibility to review Your Profile and resume to ensure that the content appears as you intend, and that it contains the right information or any information you intend to include or update. If you see any inaccuracy in any such material, it is your responsibility to correct such information or to contact VeritasKWD to do so. It may take a few days for updates to your account or Your Profile to be reflected. VeritasKWD assumes no responsibility and disclaims all liability for Your Profile or other application information you post, send or receive through the Site.</p>
                                <p>
                                    If you have a VeritasKWD account, VeritasKWD Resume and Coursework, or an uploaded file resume and coursework, you agree that VeritasKWD may associate any of this data with your VeritasKWD Profile.  Your VeritasKWD Profile consists of information you provide on the Site in the “Profile” section of your account.
                                </p>
                                <p>
                                    As we continue to improve the Site, you may be presented with the option to apply for a role using your VeritasKWD Profile. Information in your VeritasKWD Profile, except as otherwise indicated on the Site, may be available to third parties, such as Employers. If you do not want VeritasKWD to make your VeritasKWD Profile available to third parties or if you do not want Employers to contact you, set your VeritasKWD Profile to Not Active or employed. When you create or upload a new version of your resume as part of an application, VeritasKWD may automatically replace the previous resume and coursework.
                                </p>
                                <p>
                                    To mitigate fraud, VeritasKWD masks or hides your real name and substitutes it with Veritas Code91 in your resume and coursework. VeritasKWD makes no promise to you about whether all or part of your contact info will be masked or hidden, and the decision to mask or hide such info is in VeritasKWD’s sole discretion. VeritasKWD may also mask some or all of the Employer’s contact information, or an Employer may choose to mask their contact information when they contact you. In either case, you agree to an Employer contacting you from a masked phone number or email, and that you may not be able to return their call unless they provide their real number to you. VeritasKWD makes no guarantee that Your Profile will be shown to any Employer or that any portion of the VeritasKWD Profile database will be available to an Employer at any particular time.
                                </p>
                                <p>
                                    VeritasKWD may work with organizations who are involved in helping Job Seekers find opportunities. Notwithstanding the possible use of the term “partner” or “partnership,” VeritasKWD’s engagement with these organizations does not create or imply a joint venture, partnership, principal-agent relationship, or any other form of joint enterprise between the “partner” organization and VeritasKWD. In some instances, VeritasKWD shares limited information back to these organizations about Job Seekers if Job Seekers agree to such sharing. For example, confirmation that a Job Seeker has created a VeritasKWD account or used one of our Sites successfully (for example, by applying to a certain number of jobs or utilizing our career guides). These organizations may advertise their Job Seeker services in partnership with VeritasKWD. VeritasKWD is not responsible for and disclaims all responsibility and liability for the activities of these organizations and their Job Seeker services. VeritasKWD does not guarantee the quality or effectiveness of any advice, recommendations, guidance or services you may receive from these third parties. You agree that, to the maximum extent permitted by law, VeritasKWD will have no liability arising from any interactions you have with such a third-party organization.
                                </p>
                                <p>
                                    In connection with VeritasKWD’s work with these organizations, VeritasKWD may offer Job Seekers opportunities to present particular skills and qualifications on their VeritasKWD Profile in connection with training programs or courses they have taken. Job Seekers are ultimately responsible for the contents of their resumes or Profiles, as well as their job searches and applications. VeritasKWD assumes no responsibility and disclaims all liability for VeritasKWD Profiles or application information that Job Seekers share with Employers or otherwise make public. VeritasKWD makes no guarantees regarding your job application experience, that your VeritasKWD Profile or resume will be shown to a particular Employer, that Employers will contact you, or that you will receive job interviews or job offers.
                                </p>
                            </li>
                            <li>
                                <strong>Applying to Jobs Through the Site</strong>
                                <p>Any profile, resume, coursework or application information that you submit through the Site, including Personal Data included in a resume, application or responses to screener questions and assessments (“VeritasKWD Apply”), and to VeritasKWD’s Privacy Policy (all references on the Site to “Apply Now”, “Easily Apply”, “Simple Apply”, “Apply from your phone”, “Apply with VeritasKWD”, or any similar references mean “VeritasKWD Apply.”). To maintain the quality of the Site and Services, VeritasKWD in its sole discretion may impose limits on your ability to apply to Job Listings or to other VeritasKWD services. Use of any automation, scripting, or bots to automate the VeritasKWD Apply process outside of VeritasKWD’s official vendors and tooling is prohibited.</p>

                                <p>Prior to submitting your application through VeritasKWD Apply, you will be given the opportunity to review the information. It is important that you review this information carefully, including all attached files, to ensure that what is being submitted is accurate and complete, and that you are applying to your desired Employer and submitting the desired information to that Employer. You are solely responsible for the contents of the application that you submit, including all attached files. Once you provide information to an Employer (whether in the form of a job application, VeritasKWD Profile data, resume & coursework, email, interview material or otherwise), VeritasKWD does not have control over the Employer’s use or disclosure of that information. If you want to request the Employer delete, modify, or maintain confidence over any such information, you must make such a request directly to the Employer. Unsubscribing from calls from Employers through the Site does not apply to interviews you have already scheduled. If you require alternative methods for applying, you must approach the Employer directly to request such an alternative method, as VeritasKWD is not responsible for the Employer application process.</p>

                                <p>When you ask VeritasKWD to submit your application or other information through VeritasKWD Apply, you are sending your resume, coursework and application information to VeritasKWD, and you are requesting and authorizing VeritasKWD to make available such application information to the applicable Employer(s) for the indicated Job Listing(s). You further agree to VeritasKWD’s performance of automated processing in relation to your application, as such processing is an essential part of this Agreement. When you ask VeritasKWD to transmit an application or a message, including, but not limited to, a signed offer letter, to an Employer via VeritasKWD Apply or the Site’s relay system, or store such application, you understand that this is without warranty, and that VeritasKWD reserves the right to reformat such application or message. Additionally, you consent to your application and any responses sent to you by the Employer (including offer letters) through the Site being processed and analyzed by VeritasKWD according to this Agreement and VeritasKWD’s Privacy Policy.</p>

                                <p>You acknowledge and agree that Employers may request that VeritasKWD assemble your application materials, resume, coursework, answers to screener questions, assessment responses and other information you provide to VeritasKWD into one document, and you agree that in doing so, VeritasKWD assembles these application materials on your behalf. When you apply to a job using VeritasKWD Apply, VeritasKWD will attempt to send your application to the contact information provided to us by an Employer or their Agent, which may include sending your application to an Applicant Tracking System (ATS) or other service provider selected by the Employer. You agree that Employers can enable such service providers to access and manage their VeritasKWD accounts, including by connecting to and integrating with APIs provided or used by VeritasKWD. By applying for a job through the Site, you agree to Employer’s use of such service providers, and acknowledge that such use may involve an intermediary’s access to job applications sent to its Employer client. We cannot guarantee that such messages and applications will be delivered, received, accessed, read or acted upon. VeritasKWD also does not guarantee that any Employer will receive, be notified about, access, read or respond to any such resume or other application material, or that there will be no mistakes in the transmission or storage of the data. VeritasKWD depends on the Employer or the Employer’s agent to provide VeritasKWD with the correct destination for all applications, and we cannot vouch for the validity of the contact information provided to us by Employers. If the electronic destination provided to VeritasKWD is incorrect, your application materials will not be sent to the intended recipient of the application. Further, VeritasKWD does not guarantee that its integrations or the interface will be error-free. However, VeritasKWD may alert you when any of the above events occur.</p>

                                <p>Job Ads may expire or otherwise be removed between the time you submit your application and the time it is received, in which cases your application will be void. VeritasKWD has no responsibility for expired or removed Job Ads or for delivering applications prior to a Job Ad’s expiration or removal. VeritasKWD and its third-party providers may store your application and related information regardless of whether a Job Listing has been closed or is no longer available on the Site. We also cannot vouch for the technical capabilities of any third-party sites, including but not limited to ATSs. Third party sites, including ATSs used by Employers, may disclaim liability for technical malfunctions, including the failure in the delivery of applications. We are not responsible if an ATS rejects or fails to deliver an application to an Employer for any reason. If you do not feel comfortable sending an application or messages in this manner, or having your application or messages stored by VeritasKWD on VeritasKWD’s or third-party providers’ servers, do not use the VeritasKWD Apply or VeritasKWD relay functions and please send your application or messages directly to the Employer by whatever other method you so choose, including the public mail system. You may contact the Employer directly to find alternative methods of application if you do not wish to apply through the Site. By using the VeritasKWD Apply system, you fully consent to the above.</p>

                                <p>By using the Site, you agree that VeritasKWD is not responsible for the content of the Employer’s job application, requirements, messages, screener questions, skills assessments or their format or method of delivery, and that VeritasKWD does not guarantee receipt of your application by the Employer, or your receipt of messages from the Employer. Please note that VeritasKWD does not choose the questions asked by Employers or decide the job qualification criteria of Employers. If you have questions or concerns about an Employer’s application materials, please contact the Employer directly or refer to their privacy policy. VeritasKWD does not guarantee the identity of an Employer or any individuals working for any Employers, and cautions Job Seekers when applying to jobs. VeritasKWD cannot make any guarantee regarding health and safety measures in an Employer’s hiring or interviewing process. VeritasKWD recommends Job Seekers follow personal health and safety best practices as recommended by the Ministry of Health or similar institution. VeritasKWD does not guarantee the validity of a job offer and cautions Job Seekers to verify the validity of a job offer before taking an adverse action regarding their current employment situations. Job Seekers are solely responsible for verifying the accuracy of any Employer or job offer.</p>

                                <p>When you search for jobs on the VeritasKWD Job Search app and proceed to apply for a job, including jobs on third party sites, the Site may suggest information from your VeritasKWD profile to include in your application. It is your responsibility to review suggestions before accepting them and including them on your application.</p>

                                <p>You acknowledge that as part of its efforts to combat fraud and spam, VeritasKWD may require that users verify their email address. When you apply to a job through the Site, you agree that you may be required to verify your email address, and that failure to verify may lead to your application being rejected.</p>

                            </li>
                            <li>
                                <strong>Job Matching and Recommended Jobs</strong>
                                <p>Job matches are recommendations which may be presented to both you as a Job Seeker and to Employers in various formats on the Site. For example, VeritasKWD may recommend Job Ads which are similar to jobs to which you recently applied or recommend VeritasKWD Profiles to Employers which match Job Ads they post.</p>

                                <p>To generate matches, VeritasKWD uses data collected through our Site from both Employers and Job Seekers. This includes Job Ads, Your Profile information, information from your resume, coursework, your application materials, VeritasKWD Assessments, and your activity on the Site (such as searches you run and Job Ads you click on and apply to). You agree and consent that VeritasKWD may use this information to present potential matches to you and to potential Employers.</p>

                                <p>VeritasKWD may automatically send you recommended jobs via the email address you use to apply to a job or the email that is associated with your VeritasKWD account.</p>

                            </li>

                            <li>
                                <strong>Communications and Other Actions on the Site</strong>
                                <p>When you view, send, store or receive communications or materials (including Job Listings, resumes, messages, text messages, chats, emails, applications, questions and responses in applications, interview or other voice recordings or transcripts, and any other information) to, on or through the Site, you agree to your communication and materials being processed, analyzed, reviewed, and stored, including via automated means, for data analysis, quality control, enforcement of the Sites’ rules and other VeritasKWD policies, content moderation, and to improve the Site or any other VeritasKWD product or service. To achieve these purposes, we use this data to develop, train, build, and use statistical models, including artificial intelligence and machine learning models. VeritasKWD also uses vendors as an extension of the Site to collect, record, process, analyze, and store communication data. If you disagree with any part of these terms, do not use the Site.</p>

                                <p>When an Employer views, sends, stores or receives communications or materials to, on or through the Site, VeritasKWD may inform you about such actions. Additionally, we may also inform you that an Employer has taken other actions with regards to a Job Ad, Your Profile, or your application, such as pausing or closing a Job Ad, opening Your Profile or application, viewing Your Profile or application, responding to Your Profile or application, and making a decision with regards to your application or Job Ad. As part of this functionality, you may receive notifications via the app, email or platform corresponding with your or an Employer’s (in the event you applied for a job) activity on or use of the Site, VeritasKWD Apply, VeritasKWD Messaging, or any other communications service, product, or feature provided on or through the Site. In all cases, such notifications are provided solely as a courtesy, and you should not rely on them. For example, if you accept an interview request, it is your responsibility to follow up with the employer separately to ensure they know your response, do not rely on notifications through the Site. VeritasKWD disclaims all warranties with regards to the transmission or storage of such courtesy notices, does not guarantee their delivery or receipt, and does not guarantee the date or time at which they may be sent.</p>

                                <p>VeritasKWD may enable in-app messaging services (“VeritasKWD Messaging”), as well as text messaging relay, email relay, and/or call relay services through our Site directly or through vendors to help facilitate contact between Employers and Job Seekers about a Job Listing. VeritasKWD may also enable you and/or Employers to connect with each other on VeritasKWD Messaging via third-party providers. You understand that communicating through VeritasKWD Messaging and/or other communication options on or through the Site shall be limited to the purpose of applying for a Job Listing. VeritasKWD reserves the right, in its sole discretion, to turn off or disable VeritasKWD Messaging or other communication options for any Employer or Job Seeker at any time without prior notice and for any or no reason. Please note that since relay services depend on the functionality of third-party providers, there may be technical delays and other errors on the part of those providers. We cannot vouch for the technical capabilities of any third parties to send or receive communications, such as text messages, emails or calls. We also do not guarantee that VeritasKWD’s integrations with these third-party providers or interface will be error-free. Further, we do not guarantee that communications sent to or through VeritasKWD Messaging will be delivered, received, accessed, read or acted upon. However, VeritasKWD may alert you when any of the above events occur. In the event a message being sent is intended for a closed account, these messages will not be deliverable.</p>

                            </li>

                            <li>
                                <strong>Virtual Communications</strong>
                                <p>Employers may offer you the opportunity to participate in virtual, pre-recorded, and remote communications using VeritasKWD products, including but not limited to, VeritasKWD Interview, VeritasKWD Hiring Platform, Virtual Evaluations, phone interviews, virtual meetings, and video interviews (“Virtual Interviews”). You understand that VeritasKWD is not a telecommunications service provider and that VeritasKWD is only providing the option for you to communicate with Employers via services that may be offered by third-party providers. Please note that since these telecommunication services may depend on the functionality of third-party providers, there may be technical delays or malfunctions on the part of those providers. We cannot vouch for the technical capabilities of any third parties to receive, transmit, or support such phone or video communications. VeritasKWD does not guarantee any aspect of your Virtual Interview experience including transmission of phone or video communications, quality of audio/visual content, data security, or data usage and restrictions. VeritasKWD is not liable for any claims arising out of your use of Virtual Interviews and you release VeritasKWD from any such claims.</p>

                                <p>You understand that VeritasKWD does not guarantee the Employer’s schedule or availability for conducting Virtual Interviews and cannot vouch for the validity of the contact information provided to us. You also understand that the Employer is responsible for any and all questions, comments, or hiring decisions made. Further, Employers are responsible for any accommodation you need during Virtual Interviews.</p>

                                <p>NOTICE – Virtual Interviews May be Recorded: You understand that an Employer may enable the recording of a Virtual Interview, or you may be given the option to pre-record an interview to provide to the Employer. You agree to respect any notification (visual, audio, or otherwise) which may indicate that recording is enabled by or on behalf of an Employer on Virtual Interview. If you do not agree to be recorded, you must refrain from pre-recording an interview or you must immediately leave the Virtual Interview. By using Virtual Interviews, you agree that the Virtual Interview may be recorded and that VeritasKWD and third-party providers can store, access and analyze the recording. Also, you agree that an Employer that receives pre-recorded interviews or activates the recording function, can access, store, use, analyze, and share the recording, and that this activity is outside of VeritasKWD’s control. You further agree that VeritasKWD is not liable for any claims arising out of the recording of virtual interviews, and you release VeritasKWD from any such claims.</p>

                                <p>you understand and agree that, to the maximum extent permitted by law, there is no protection for any information you share or data that you transmit while participating in virtual interviews including, but not limited to, audio/visual content, interview questions and answers, or your image or likeness. You acknowledge and agree that, to the maximum extent permitted by law, VeritasKWD is not responsible for securing or protecting any data or information that you share or transmit during your use of virtual interviews. VeritasKWD assumes no liability for the misuse of any data you share or transmit through use of virtual interviews. You further acknowledge and agree that VeritasKWD does not assume any responsibility for availability or retention of any recordings of virtual interviews. You understand and agree that you access and use virtual interviews at your own discretion and risk and that VeritasKWD disclaims all liability arising out of your use of virtual interviews.</p>

                            </li>

                            <li>
                                <strong>Job Seeker services</strong>
                                <p>VeritasKWD may offer you resume review, resume scan, offer coaching, live video consulting sessions, writing services, general career guidance, or other consultation services (collectively, “Job Seeker services”). By using Job Seeker services, you request and consent that VeritasKWD, or a VeritasKWD vendor, provide you with the service you select. You may only use Job Seeker services for advice concerning your own resume, coursework, offer, or employment situation and not another person’s. As a user of the Site, VeritasKWD may also, from time to time, provide you career or hiring guides via blog posts, email, or other channels as part of its services to you. For example, VeritasKWD may provide tips on improving your resume or how to use your resume effectively in the job application process, commonly asked interview questions, next steps after you have submitted an application, and how to prepare for a new job after you have been hired. VeritasKWD offers these Job Seeker services as optional guidelines for its users and all liability with respect to actions taken or not taken based on the contents of such Job Seeker services are hereby expressly disclaimed.</p>

                                <p>When filling out forms associated with Job Seeker services, you agree to provide complete and accurate information. Any information you upload through the forms, including a resume, coursework, constitutes User Content and shall be treated in accordance with any User Content sections herein. Any career-related or hiring-related information, feedback, guides or other content provided by VeritasKWD, or VeritasKWD’s vendor, through Job Seeker services or otherwise, is for informational purposes only, and is in no way to be construed as professional career counseling or staffing services. You understand that VeritasKWD may give suggestions or information regarding best-practices, however, you understand that it is ultimately your responsibility to determine how to pursue your job search or candidate search. You further understand that in providing any such career or hiring guides, VeritasKWD is not acting as a job placement agency or staffing firm. You are responsible for reviewing any career or hiring-related information provided to you, for example, for accuracy and completeness. You are also responsible for editing the information before you use it, for example, for an employment application. VeritasKWD is not responsible for the accuracy or completeness of any information that VeritasKWD or its vendor provides you with. You understand that by using Job Seeker services or referring to or using any career or hiring information, you are not guaranteed job interviews, job placement, assurance of being hired, or a higher salary or increased benefit, and you take full responsibility for use of these services or information.</p>

                                <p>VeritasKWD owns all rights in VeritasKWD Services and products, and other career and hiring-related material that VeritasKWD provides you with, such as video feedback and hiring tips. By using Job Seeker services, VeritasKWD grants you an express, non-exclusive, non-assignable, and non-sublicensable right and license to use materials developed by VeritasKWD or VeritasKWD vendors for you. This license is limited to personal and non-commercial use and any further use is prohibited.</p>

                                <p>VeritasKWD may offer, as part of Job Seeker services, the opportunity for you to engage with third parties, sometimes referred to as career coaches or professional writers, to discuss job search, resume writing, or career strategies, either through the Site or in person. Regardless of how you interact with them, you acknowledge that these third parties are not employees of VeritasKWD and that VeritasKWD is not responsible for the content of any such discussion, or any actions taken or not taken based on the contents of such discussion. Do not share any information you consider confidential or personally sensitive with these third parties. VeritasKWD does not guarantee the quality or effectiveness of any advice, recommendations, or guidance you may receive from these third parties. You agree that, to the maximum extent permitted by law, VeritasKWD will have no liability arising from any discussion you have with such a third party.</p>

                            </li>

                            <li>
                                <strong>Salary and Other Information Provided by VeritasKWD</strong>
                                <p>VeritasKWD may provide salary and other information and content to users for informational purposes only. For example, VeritasKWD may provide you with data regarding estimated salaries for a given Job Listing, number of applies to a Job Listing, responses to certain screener questions for a Job Listing, or the likelihood that a particular event will occur such as being selected for an interview. This information provided by VeritasKWD is based on estimates given for informational purposes only and without warranty and is subject to change or varying levels of accuracy. Please note that all salary figures displayed on the Site are approximations based upon multiple third-party submissions to VeritasKWD, including from VeritasKWD affiliates. These figures are given to VeritasKWD users for the purpose of generalized comparison only.</p>

                                <p>VeritasKWD, in its sole discretion, may add labels or badges to Employer names or Job Ads, such as, “Responsive Employer” or “Active Employer” or “Hired on VeritasKWD” or “Verified”. Employers may also request that VeritasKWD add such labels. VeritasKWD shall determine the method by which such labels or badges are determined, or which Employers qualify. The lack of a label or badge may indicate that VeritasKWD does not have sufficient data to determine if an Employer qualifies. Some of the data may be provided by the Employer and VeritasKWD does not guarantee the accuracy of such data. VeritasKWD does not guarantee the accuracy of any label or badge that is added to Employer names or Job Ads. VeritasKWD may add labels or badges to Job Ads – such as pay types, specialties, benefits, or union associations – based on data contained within the job description for informational purposes only. VeritasKWD does not guarantee the accuracy of any label or badge that is added to Employer names or Job Ads, including data on Job Ads.</p>

                                <p>VeritasKWD may also display publicly available information about employers on Company Pages. Information on Company Pages is presented for informational and promotional purposes only, is subject to change, and may be gathered from or generated by third parties. Please contact the Employer for the most accurate and up-to-date company information.</p>

                            </li>
                            <li>
                                <strong>Your Job Seeker Data</strong>
                                <p>As a Job Seeker, you take a variety of actions on our Site and you provide various information. For example, you search for jobs, and VeritasKWD knows and stores the titles of jobs you search for and click on, where those jobs are located, the general salary range or experience level of the jobs you view (if indicated on the Job Listings), the Job Listings you apply to, your amount of activity or time of most recent activity on the Site, and any other information you provide directly to VeritasKWD including desired salary, past experience, any information in your VeritasKWD Profile, and any of your other behavior on the Site. You know exactly what this data is because you are the person who provided the information or undertook the activity and the data pertains only to your activity. By using the Site, you acknowledge and agree that VeritasKWD collects, records, processes, analyzes, and stores any and all information you provide and activities you take on the Site, and any and all interactions and communications you have with, on, or through the Site. You further acknowledge and agree that VeritasKWD may inform the Employer about activities you take on the Site or your use of the Site, for example, whether you are online, recently active, or active on VeritasKWD, and whether you are responsive to Employer messages on VeritasKWD.</p>

                                <p>When you initiate a job application on a website operated by an Employer or its applicant tracking system, VeritasKWD may collect certain information about you and any actions taken by you during your visit using automated means, such as via API, cookies, pixels and web beacons. The information collected includes, for example, information about Job Listings you viewed and job applications you started and completed. An Employer who provides tracker functionality is required under this Agreement to provide any notice, and obtain any prior consent, that may be required by applicable law. However, you acknowledge and agree that VeritasKWD has no control over such an Employer or its website. You agree to VeritasKWD’s use of, and receipt of information from, any such tracker functionality.</p>

                                <p>You agree that any data contained in or associated with Your Profile may be used to suggest jobs to you and to suggest you or your Profile to Employers that might be interested in a person who matches your behavior on the Site.  You also agree that VeritasKWD may contact you based on this observed behavior or provided info on behalf of Employers or VeritasKWD itself. Please note, the aforementioned actions do not include information sent to you by a third party, however, VeritasKWD may publicly display the fact that you have recently used the VeritasKWD Site to correspond with a third party. In addition, if Your Profile is set to Searchable, this means that VeritasKWD may share all of the aforementioned information about yourself with third-party Employers. If you do not wish to share such information, you may set Your Profile to Not Searchable. When you make changes to your VeritasKWD Profile, including, but not limited to, updating, deleting, or changing settings, it may take a few days for the changes to be reflected.</p>

                                <p>VeritasKWD, in its sole discretion, may add labels or badges to Job Seeker profiles, such as “Responsive Candidate” or “New Applicant.”  VeritasKWD determines the method by which such labels or badges are added, or which Job Seekers qualify based solely on Job Seeker activity on VeritasKWD. The lack of a label or badge may indicate that VeritasKWD does not have sufficient data to determine if a Job Seeker qualifies. VeritasKWD does not guarantee the accuracy of any label or badge and reserves the right to change or remove such label or badge features at any time and in VeritasKWD’s sole discretion.</p>

                                <p>You may have the opportunity to provide VeritasKWD with certain demographic information about yourself, such as your race and ethnicity, gender, age, LGBTQ+ community membership, and disability status, as well as whether you have an arrest or conviction record (“demographic data”). By choosing to provide your demographic data you agree that VeritasKWD may use it to evaluate and improve our products and share aggregate summaries of job seeker information with employers. If you do not want your demographic data to be used in this way, do not provide it to VeritasKWD (or, if you have already provided your demographic data to VeritasKWD, you can request it be removed). You further acknowledge and agree that another Job Seeker’s demographic data is personal information, and to the extent permitted by law you waive any right to request or view demographic data pertaining to any other Job Seeker.</p>

                                <p>Please note that VeritasKWD may be required to comply with legal obligations or governmental requests or to establish or exercise its legal rights or defend against legal claims. This means, for example, that VeritasKWD may receive legal process from courts or law enforcement to reveal user data, including demographic data.</p>

                                <p>Please also note that some Employers may ask applicants to voluntarily self-identify certain demographic information such as race, ethnicity, sex, and disability along with their job applications. Some Employers are required by law to ask these questions, and you may see these questions when applying to jobs on VeritasKWD. That is a separate process from VeritasKWD’s collection of demographic data, and VeritasKWD is not responsible for these questions. If you have questions or concerns about an Employer’s application materials, please contact the Employer directly or refer to their privacy policy.</p>

                            </li>

                            <li>
                                <strong>VeritasKWD Hiring Platform</strong>
                                <p>VeritasKWD Hiring Platform is a platform designed to streamline Employer hiring and employment decision-making processes by allowing users access to various products such as VeritasKWD Interview and related services (“VeritasKWD Hiring Platform”). Employers may offer you the opportunity to participate in hiring activities that might be supported by VeritasKWD Hiring Platform. You acknowledge and understand that Employers select the method and manner that VeritasKWD Hiring Platform will be used for its job openings and that the Employer determines the job requirements and specific needs of its hiring efforts.</p>

                                <p>You understand and agree that employer is responsible for complying with applicable law regarding its employment and hiring practices and that employer indemnifies VeritasKWD against any and all claims arising from employer’s use of VeritasKWD hiring platform or similar products. VeritasKWD disclaims all liability and makes no warranty that employer’s use of the services complies with Kenya laws. VeritasKWD has no control nor participates in the hiring or decision-making process regarding Employer hiring efforts. Further, you understand that VeritasKWD is not an employment agency by offering VeritasKWD Hiring Platform and related tools.</p>

                                <p>By using VeritasKWD Hiring Platform, you understand that VeritasKWD is not procuring employees for Employer or opportunities for Job Seekers. VeritasKWD merely provides VeritasKWD Hiring platform as a tool that enables Employers and Job Seekers to exchange information as they determine.</p>

                            </li>

                            <li>
                                <strong>Governing Law and Dispute Resolution</strong>
                                <p>
                                    This Agreement and any dispute arising out of or in connection with this Agreement or related in any way to the Site (“Dispute”) will be governed as to all matters, including, but not limited to the validity, construction and performance of this Agreement, by and under the laws of the Republic of Kenya. Any and all actions, lawsuits, or other legal proceedings related to such Dispute shall be filed only in courts located in Machakos, Kenya. The application of mandatory provisions limiting the choice of law and in particular the application of mandatory laws of the country in which you have your habitual residence, such as consumer protection laws, shall remain unaffected.
                                </p>
                            </li>

                            <li>
                                <strong>Class Action Waiver</strong>
                                <p>By using the Site or any Program Elements (defined below) and in return for the services offered by VeritasKWD, you acknowledge that VeritasKWD can only offer you these services under the terms and conditions as presented herein. As partial consideration for your use of the Site and the Publisher Program, you agree not to sue VeritasKWD as a class plaintiff or class representative, join as a class member, or participate as an adverse party in any way in a class-action lawsuit against VeritasKWD regarding your use of the Site. Additionally, as a Job Seeker, you acknowledge that your use of job search, VeritasKWD Apply, and other services on the Site is by a one-time subscription fee. Your acceptance of this Agreement, including this Class Action Waiver, is an essential part of the bargain allowing your free use of the Site. If you do not agree to any part of these terms, do not continue your use of the Site.</p>
                            </li>
                        </dl>


                        <p className="text-2xl font-bold mt-10">Terms of Service for Employer</p>
                        <p>The following terms and conditions apply to all Employers and other users who access or use the Site as intended for individuals and/or organizations seeking to make available information regarding employment openings, on their behalf or other’s behalf, or otherwise indicate their acceptance to this Agreement. </p>
                        <p>For purposes of this section, all references to “you” or “your” shall mean you, the individual or organization accessing this Site in your capacity as an Employer or other user as described above.</p>
                        <dl>
                            <li>
                                <strong>Employer Accounts</strong>
                                <p>When you create a VeritasKWD account, a Company Page or post job listings advertising employment opportunities and other job-related contents, including links to third-party websites (“Job Listings” or “Job Ads”) on the Site, whether as part of the VeritasKWD Ads Program or otherwise, you agree that this Agreement, the terms associated with any VeritasKWD service you are using, and all of VeritasKWD’s policies, including the VeritasKWD Privacy Policy, apply to you.</p>

                                <p>When you create a VeritasKWD account, VeritasKWD may require that you verify your identity. You may be presented with different options for verification, including verification via phone or email.</p>

                                <p>When you access or use the Site in your capacity as an employee or other representative of an Employer, or if you create a VeritasKWD account on behalf of an Employer, you represent and warrant that you have the authority to bind the Employer to this Agreement. When you create an account on behalf of an Employer, the account belongs to the Employer, and you acknowledge that any and all information that you provide VeritasKWD through the account, such as the actions you take and when you take them, will be visible to the Employer. As part of this account, you may have an individual profile (“Employer Profile”). Your Employer Profile consists of information you provide on the Site in the “Account Settings” and “Employer Settings” section of the account.</p>

                                <p>As an Employer, your account is for business use and not for personal use. VeritasKWD is not responsible for and disclaims all liability if your email is used improperly or falsely by a third party. By registering for a VeritasKWD account, you agree to receive mandatory email updates regarding account activity to your VeritasKWD account. If you attempt to send an email from a name or email address that is not true, accurate, current or complete, we reserve the right to drop such email, and attempting to send such email is a violation of our terms. Employers may request that VeritasKWD disable an account at any time by contacting VeritasKWD support. Please note that VeritasKWD may be required to preserve business records pertaining to that account to comply with its obligations under law.</p>

                                <p>You agree that VeritasKWD may send notices to Job Seekers informing them that an Employer account has been compromised, including if such account is associated with you. VeritasKWD cannot and does not guarantee that such notices will always be sent or received, and you therefore agree that VeritasKWD bears no responsibility for doing so. VeritasKWD makes no warranty regarding, and disclaims any liability for, the accuracy, completeness, timeliness, or reliability of such notices.</p>

                                <p>VeritasKWD may offer suggestions, recommendations, or information to users that may support or improve their experience on VeritasKWD Sites. You understand that these offerings are provided as a courtesy and without warranty, and your use of such information is at your sole discretion. As an Employer, you are responsible for your use of the Site and any tools offered therein, including your decisions regarding your job description, the requirements for your job, compliance with applicable laws, including relevant national, county, and local laws related to job postings, and whom you interview or hire. VeritasKWD assumes no responsibility and disclaims all liability for any actions you take based on any information provided by VeritasKWD. VeritasKWD may limit your ability to post a job, or the visibility of your job, if it does not appear to indicate a salary above minimum wage, wage transparency laws, or does not comply with other applicable law; however, VeritasKWD is not responsible for, and you are solely responsible for, compliance with Kenya labor laws.</p>

                                <p>You agree that VeritasKWD is not responsible for maintaining or storing employment records, job application materials or data on your behalf, and that you are responsible for your own compliance with any applicable record retention requirements or other applicable law.</p>

                                <p>If you close or change any Job Listings that you post, you agree to promptly update such Job Listings on the Site or otherwise notify VeritasKWD. VeritasKWD may provide you with a mechanism for responding to requests for accommodations from Job Seekers. You are responsible for ensuring that your selection criteria are job-related, that you do not pose “disability-related inquiries” or medical inquiries in violation of the law, and that you do not screen out people with disabilities or members of any protected category under the law. You are responsible for clearly indicating that reasonable accommodations are available, engaging with and responding to any requests for accommodation, and providing information about how to request an accommodation to Job Seekers.</p>

                                <p>You agree that VeritasKWD may reject or remove any Job Listing or any questions for Job Seekers for any or no reason. For example, VeritasKWD may remove any Job Listing or question that directly or indirectly discriminates against Job Seekers. Direct discrimination means, for example, that a Job Listing, requirement, or question specifically makes clear that only Job Seekers matching certain criteria are wanted, thereby excluding others because of, for example, their gender, race, age or disability. Indirect discrimination means, for example, that a Job Listing, requirement, or question implicitly excludes certain classes of Job Seekers by making it impossible for them to qualify for the job requirements. You understand and agree that it is your responsibility to refrain from posting any Job Listing, requirement, or question that directly or indirectly discriminates against Job Seekers or otherwise violates applicable law. You understand and agree that you are responsible for ensuring that your Job Listing requirements and criteria are job-related and in compliance with applicable law. VeritasKWD does not guarantee delivery, your receipt of the Job Seeker’s emails or application materials, or that there will be no mistakes in the transmission or storage of the data. You are solely responsible for checking your Employer dashboard to view job applications and other information. Any notifications, such as emails, you may receive about applications or other activities, are provided solely as a courtesy to you and you should not rely on them.</p>

                                <p>When you use VeritasKWD Apply for your Job Listings, you acknowledge and agree that VeritasKWD may add functions into the corresponding VeritasKWD Apply emails. In addition, VeritasKWD may, on your behalf, send out reminder emails to Job Seekers you wish to interview. VeritasKWD may also send emails to Job Seekers on your behalf indicating that your Job Listing is potentially a match for the Job Seeker’s resume.</p>

                                <p>Similarly, you may be given the option to use candidate management tools that schedule interviews on your behalf with Job Seekers who meet criteria you have selected. If you choose such option, Job Seekers will be scheduled for interviews and invited to interviews on your behalf via email based on whether information the Job Seeker has provided to VeritasKWD (e.g., answers to screener questions, resume, VeritasKWD Assessment Responses) matches criteria you have set. You are responsible for ensuring that your selection criteria are job-related, that you do not pose “disability-related inquiries” or medical inquiries in violation of the law, and that you do not screen out people with disabilities or members of any protected category under the law. You further agree that VeritasKWD has no discretion in the transmission or storage of these interview invitations (which are purely mechanical), that transmission or storage is not guaranteed, and that the information the Job Seeker provided to VeritasKWD may not be accurate. VeritasKWD may request that Job Seekers confirm their interest in the position before scheduling an interview. It is ultimately the Employer’s responsibility to confirm whether any interviews were scheduled, or to reschedule or cancel interviews if necessary. The decision of who to interview is decided solely by the Employer, who can choose to interview any Job Seeker at any time, and by scheduling such interviews, VeritasKWD does not warrant that a Job Seeker is qualified, meets the criteria the Employer has set, or that the information provided by the Job Seeker to VeritasKWD is accurate. VeritasKWD candidate management tools are intended to allow Employers to more efficiently connect with Job Seekers as they determine, and the sole responsibility for the content of any screener question, any decision to proceed or not proceed with interview or offers, any issues arising from an acceptance or denial of employment, and any other issues arising from the use of candidate management tools is solely with the Employer. By using this and other candidate management tools, you acknowledge and agree that VeritasKWD is not procuring employees for Employers or procuring opportunities to work for Job Seekers, and that VeritasKWD does not act as your employment agency by offering these candidate management tools.</p>

                                <p>VeritasKWD may highlight to Job Seekers qualifications required for your position in order to help the Job Seekers assess whether to apply for your role. VeritasKWD does not verify the identity of any Job Seekers who apply to your job listing, nor does VeritasKWD know a Job Seeker’s motivation for applying to your job listing, and thus provides no guarantee as to the Job Seeker’s qualifications or interest in your job listing. You agree that VeritasKWD Apply and VeritasKWD’s relay functions are presented to you without warranty and VeritasKWD assumes no responsibility for the communications between you and the Job Seeker, which communications are your and the Job Seekers’ sole responsibility.</p>

                                <p>You shall indemnify, defend and hold harmless VeritasKWD, its agents, affiliates, and licensors from any third-party claim or liability (including without limitation reasonable legal fees) arising out of any Company Page created or claimed by you, or any Job Listing, application materials, voluntary self-identification questions, or screener questions (or answers thereto) posted by you, or any message sent by you. VeritasKWD may make Job Ad analytics data available on a Company Page or elsewhere on the Site and may provide analytics data regarding your Employer account to anyone at your company at VeritasKWD’s discretion. To the extent permitted by law, if you have an unpaid or outstanding invoice or account balance for any VeritasKWD product, VeritasKWD reserves the right to suspend or terminate your use of that VeritasKWD product as well as any other VeritasKWD product as set out in the IO for that product, including but not limited to those VeritasKWD products where you do not have an unpaid invoice or account balance.</p>

                                <p>When you view, send, take action on, make a decision regarding, store, or receive materials (including Job Listings, resumes, applications, pre-recorded interviews, and messages) through or using the Site or any Applicant Tracking System (“ATS”), VeritasKWD may, for any purpose, use any data of such materials or action for data analysis, quality control, or to refine the Site or any other VeritasKWD product or service (including to provide better search results and other Job Listings for Job Seekers and Employers), whether via automated means or otherwise. VeritasKWD may also inform the Job Seeker of your actions or activity related to such materials through or using the Site or any ATS. For example, VeritasKWD may notify the Job Seeker about your activity or action related to a Job Ad (such as pausing or closing it), or Job Seeker’s application or Resume (for example, that you viewed or responded to it, or that you made a decision with respect to it). VeritasKWD may inform Job Seekers about activities you take on the Site, for example, whether you are online, recently active, or active on the Site. You hereby consent to VeritasKWD informing the Job Seeker about such actions and activities.</p>

                                <p>VeritasKWD, in its sole discretion, may add labels or badges to Employer names or Job Ads, such as, “Responsive Employer” or “Active Employer” or “Hired on VeritasKWD” or “Verified”. Employers may also request that VeritasKWD add such labels. VeritasKWD shall determine the method by which such labels or badges are added, or which Employers qualify. The lack of a label or badge may indicate that VeritasKWD does not have sufficient data to determine if an Employer qualifies. Some of the data may be provided by the Employer and VeritasKWD does not guarantee the accuracy of such data. VeritasKWD does not guarantee the accuracy of any label or badge that is added to Employer names or Job Ads. VeritasKWD reserves the right to change or remove such label or badge features at any time and in VeritasKWD’s sole discretion.</p>

                            </li>

                            <li>
                                <strong>Job Match</strong>
                                <p>Job matches are recommendations which may be presented to both you as an Employer and to Job Seekers in various formats on the Site. For example, VeritasKWD may recommend Resumes and Coursework which match Job Ads you have posted or recommend Job Ads to Job Seekers which are similar to jobs to which they have recently applied. </p>
                                <p>To generate matches, VeritasKWD uses data collected through our Site from both Employers and Job Seekers. This includes Job Ads, Resume, Coursework, application materials, VeritasKWD Assessments, and user activity on the Site (such as searches run and Job Ads clicked on and applied to). You agree and consent that VeritasKWD may use this information to present potential matches to you and to potential Job Seekers. VeritasKWD’s matches uses the ONET classification of the Unites States of America.</p>
                            </li>

                            <li>
                                <strong>Salary, Applies or Other Information Provided by VeritasKWD</strong>
                                <p>VeritasKWD may provide some information and content to users for informational purposes only. For example, VeritasKWD may provide Job Seekers with data regarding estimated salaries for a given Job Listing, number of applies to a Job Listing, or provide you with estimated applies to your Job Listing. All such figures provided by VeritasKWD are estimates given for informational purposes only, may come from a third party, and they are subject to change or varying levels of accuracy.</p>

                                <p>VeritasKWD may add labels or badges to Job Ads – such as pay types, specialties, benefits, or union associations – based on data contained within the job description. These are for informational purposes only and VeritasKWD does not guarantee the accuracy of any label or badge. VeritasKWD may also include salary estimations on pages other than Job Listings on the Site.</p>

                                <p>VeritasKWD may offer job post templates for informational purposes only. By using any of this content, you adopt it as your own and are responsible for making it true, appropriate and compliant with all applicable laws. All content provided by VeritasKWD, including template job post information and estimated applications for a given job posting, is for informational purposes only, may comprise or be based on information provided by third parties, is provided without warranty, and is subject to change and varying levels of accuracy. Estimated applications are not a guarantee of future performance.</p>

                                <p>VeritasKWD, in its sole discretion, may add labels or badges to Job Seeker profiles, such as “Responsive Candidate” or “New Applicant.” VeritasKWD determines the method by which such labels or badges are added or which Job Seekers qualify based solely on Job Seeker activity on VeritasKWD. The lack of a label or badge may indicate that VeritasKWD does not have sufficient data to determine if a Job Seeker qualifies. VeritasKWD does not guarantee the accuracy of any label or badge and reserves the right to change or remove such label or badge features at any time and in VeritasKWD’s sole discretion.</p>

                                <p>VeritasKWD may offer functionality that groups candidates based on whether they meet or may meet Employers’ criteria, based on text in their resumes and coursework or answers to screener questions, and we offer Employers the ability to automatically schedule calls with applicants who meet their criteria as well. In all cases, Employers can view any applicant at any time, and VeritasKWD makes no decisions about any applicant. You agree that such functionality does not constitute or contribute to a decision and is not a substitute for human discretion and review. You agree not to use such functionality as the sole factor, as a factor weighted more than other factors, or to modify or overrule conclusions derived from other factors, in your decision-making or hiring processes.</p>

                            </li>
                            <li>
                                <strong>Shortlisting and Communication</strong>
                                <p>VeritasKWD may shortlist candidates for employers at a fee. The employer makes the ultimate hiring decision and VeritasKWD is not liable for wrong choices.</p>

                                <p>VeritasKWD may enable VeritasKWD Messaging, as well as text messaging relay, email relay, and/or call relay services through our Site directly or through vendors to help facilitate contact between Employers and Job Seekers about a Job Listing. VeritasKWD may also enable Employers and/or Job Seekers to connect with each other on VeritasKWD Messaging via third-party providers. You understand that communicating through such VeritasKWD Messaging and/or other communication options on or through the Site shall be limited to the purpose of hiring for a Job Listing. VeritasKWD reserves the right to turn on or enable VeritasKWD Messaging and/or other communication options for select Employers or Job Listings, in its sole discretion, and to notify Job Seekers that VeritasKWD Messaging or other communication options are available for a particular job or Employer. For example, you may be eligible to enable VeritasKWD Messaging pre-apply to certain Job Listings. To remain eligible for VeritasKWD Messaging pre-apply, you must respond to Job Seeker communication in the amount of time identified on the Site. VeritasKWD may, in its sole discretion, turn off or disable VeritasKWD Messaging for any Employer or Job Seeker at any time without prior notice and for any or no reason. Please note that since messaging relay services depend on the functionality of third-party providers, there may be technical delays and other errors on the part of those providers. We cannot vouch for the technical capabilities of any third parties to send or receive communications, such as text messages, emails or calls. We also do not guarantee that VeritasKWD’s integrations with these third-party providers or interface will be error-free. Further, we do not guarantee that communications sent to or through VeritasKWD Messaging will be delivered, received, accessed, read or acted upon. However, VeritasKWD may alert you when any of the above events occur. In the event a message being sent is intended for a closed account, these messages will not be deliverable.</p>

                                <p>VeritasKWD masks or hides job seeker’s name and substitutes it with a code. For example, VeritasKWD may mask Job Seeker’s name from resumes, coursework or applications.</p>

                                <p>VeritasKWD may offer you the option to manage virtual and remote communications with Job Seekers within VeritasKWD products, including but not limited to, VeritasKWD Interview, VeritasKWD Hiring Platform, phone interviews, virtual meetings, and video interviews (“Virtual Interviews”). Services may include giving you access to scheduling, video conferencing, web conferencing, meeting rooms, pre-recorded videos, pre-recorded audios and other collaborative services offered by third-party telecommunications service providers. You understand that VeritasKWD is not a telecommunications service provider. VeritasKWD disclaims all warranties with regards to the transmission of virtual communications. VeritasKWD does not guarantee (1) availability of such services at the time You attempt to initiate them (2) the quality of such services, or (3) the dates or times you’ve arranged with Job Seekers for your Virtual Interview. Further, VeritasKWD does not verify the identities or qualifications of Job Seekers with whom you arrange Virtual Interviews.</p>

                                <p>You understand and agree that, to the maximum extent permitted by law, there is no protection for any information you share or data that you transmit while participating in virtual interviews including, but not limited to, audio/visual content, interview questions and answers, or your image or likeness. You acknowledge and agree that, to the maximum extent permitted by law, VeritasKWD is not responsible for securing or protecting any data or information that you share or transmit during your use of virtual interviews. VeritasKWD assumes no liability for the misuse of any data you share or transmit through use of virtual interviews. You further acknowledge and agree that VeritasKWD does not assume any responsibility for availability or retention of any recordings of virtual interviews.</p>

                                <p>You understand and agree that you access and use virtual interviews at your own discretion and risk and that VeritasKWD disclaims all liability arising out of your use of virtual interviews.</p>

                                <p>Upon your request, VeritasKWD may extend invitations to additional representatives at your company to join Virtual Interviews. You understand and agree that VeritasKWD will extend such invitations on your behalf based on the email addresses you provide for those representatives, but VeritasKWD is not responsible for inaccuracies in the contact information you provide. Further, VeritasKWD is not responsible, and you are solely responsible for the conduct or actions of your representatives. You represent that you have the authority to bind your additional representatives to VeritasKWD’s Terms, and by extending invitations to your representatives, you are binding them to VeritasKWD’s Terms.</p>

                                <p>You understand that VeritasKWD is only providing the option for you to communicate with Job Seekers via services that may be offered by third-party providers. VeritasKWD is not a party to your Virtual Interviews and is not a participant in any arrangements you make with Job Seekers. You are responsible for any requests for accommodations from Job Seekers. For example, if a sign language interpreter is requested, it is your responsibility to provide one if you are legally obligated to.</p>

                                <p>Recording Virtual Interviews: As an Employer, you may be presented with an option to enable recording of Virtual Interviews. You acknowledge and agree that you will not record, store, or analyze Virtual Interviews without permission from Job Seekers and all participants. By recording a Virtual Interview, you represent and warrant to VeritasKWD that you have secured all necessary consent and will comply with all applicable laws, to record interviews and phone calls. By choosing to record Virtual Interviews through the Site, you agree that third-party providers and VeritasKWD can store and access the recording. However, you agree that VeritasKWD is not obligated to store or retain any recording of a Virtual Interview. You further agree to defend, indemnify and hold VeritasKWD harmless from any allegations, claims, actions, suits, demands, damages, liabilities, obligations, losses, settlements, judgments, costs and expenses (including without limitation attorneys’ fees and costs) that arise from the recording of virtual interviews.</p>

                                <p>Virtual Evaluations: You shall only use the recordings and other information obtained through Virtual Evaluations for your internal hiring purposes. You shall not use Virtual Evaluations for any illegal, discriminatory or fraudulent purpose. As part of Virtual Evaluations, you will submit or approve interview questions which VeritasKWD will share with candidates. You agree that the interview questions are part of your application process and determined solely by you. VeritasKWD may provide you with the ability to directly invite candidates to participate in Virtual Evaluations or you may instruct VeritasKWD to automatically invite candidates who meet your selection criteria, for example, all candidates who submit an application through the Site. You acknowledge and agree that you are solely responsible for your use of Virtual Evaluations, including how you decide which candidates shall be invited to participate in Virtual Evaluations, who you decide to contact after the Virtual Evaluation has been completed and any employment related decisions that you make. VeritasKWD does not act as your employment agency by offering you the Virtual Evaluations service. A candidate’s Virtual Evaluation video will only be deemed complete and submitted to you when the candidate approves the submission through the Virtual Evaluations tool. VeritasKWD reserves the right to not submit a candidate’s response if a candidate or Employer uses the tool in an abusive manner, which shall be determined in VeritasKWD’s sole discretion. You agree that VeritasKWD is not responsible for maintaining or storing any candidate submissions through Virtual Evaluations, and that you are responsible for your own compliance with any applicable record retention requirements. You acknowledge and agree that the video recordings and transcripts associated with Virtual Evaluations will only be retained for a period of one year from the date that the recording is completed by the Job Seeker (“One Year Period”). After the relevant One Year Period, the video recording and transcript will be permanently deleted and you will no longer be able to view or access them. You acknowledge that the Virtual Evaluations video recordings contain personal and confidential information, and you confirm that those you’re sharing the Virtual Evaluations video link with have permission to view the recording. The term User Content as defined in these Terms of Service shall include the content of the interview questions, as well as the content of the Virtual Evaluations video recordings, transcripts and any other information that you or a Job Seeker sends through Virtual Evaluations.</p>

                            </li>

                            <li>
                                <strong>Company Pages, Enhanced Profiles, Employer Branding Hub</strong>
                                <p>When you post a Job Ad directly on the Site, VeritasKWD. You understand that VeritasKWD may display publicly available information about your company on the Company Page, in accordance with applicable law. You authorize VeritasKWD to claim such Company Page for you on your behalf, which will be marked as a “Claimed Profile” (or similar wording) and allows you to edit and add information to the Company Page. Company Pages allow User Content (as defined below) to be posted by individuals that may not be affiliated with the Company identified on the Company Page. Additionally, VeritasKWD may include all of your Job Ads posted on the Site on your Company Page, including those posted directly on the Site as well as those indexed by VeritasKWD from other sources. You agree that you are solely responsible for any content you edit or put on a Company Page, whether generated by or for you, including photograph(s) or videos you provide, and third-party websites reachable from content you put on a Company Page.</p>
                                <p>VeritasKWD may offer some Employers the opportunity to be displayed more prominently, or in an enhanced way, on the Site (“Featured Employer”). Featured Employer is awarded at VeritasKWD’s sole discretion. The ability to receive a Featured Employer designation, generally, is a function of the number of Ads and amount you spend on the Site. The Featured Employer program may be changed or removed by VeritasKWD at any time, at VeritasKWD’s sole discretion and without notice.</p>

                            </li>

                            <li>
                                <strong>Governing Law and Dispute Resolution</strong>
                                <p>This Agreement and any Dispute arising out of or in connection with this Agreement or related in any way to the Site will be governed as to all matters, including, but not limited to the validity, construction and performance of this Agreement, by and under the laws of Republic of Kenya.</p>
                                <p>You agree to waive your right to file a pre-suit discovery proceeding seeking a user’s identifying information from VeritasKWD.</p>
                            </li>
                            <li>
                                <strong>Class Action Waiver</strong>
                                <p>By using the Site and in return for the services offered by VeritasKWD, you acknowledge that VeritasKWD can only offer you these services under the terms and conditions as presented herein. As partial consideration for your use of the Site and these services, you agree not to sue VeritasKWD as a class plaintiff or class representative, join as a class member, or participate as an adverse party in any way in a class-action lawsuit against VeritasKWD regarding your use of the Site. If you do not agree to any part of these terms, do not continue your use of the Site. </p>
                            </li>
                            <li>
                                <strong>Indemnification</strong>
                                <p>You shall indemnify, defend and hold harmless VeritasKWD, its agents, affiliates, and licensors from any claim or liability (including without limitation reasonable legal fees) arising out of or related to: (a) your violation of any term of this Agreement; (b) your use of, and access to, the Site or any VeritasKWD product, program, or service; (c) your loss of, or disclosure of, information gained from using the Site or any VeritasKWD product, program, or service; (d) your violation of any applicable employment, equality, or discrimination laws, and any applicable data protection or privacy laws (this includes any claims that VeritasKWD as your agent violated any such laws); (e) your violation of any third party right, including without limitation any copyright, property, or privacy right; (f) any claim that your content caused damage to a third party; (g) your actions as an Employer, including without limitation doing or not doing the following: screening, hiring, promoting, or demoting any employee or Job Seeker; or (h) the activities of any third-party service providers you engage to assist you with activities related to your use of VeritasKWD products and services, such as, but not limited to: facilitate your sourcing activities or track the conversion rates of job seeker through to job applicant. This defense and indemnification obligation will survive this Agreement and your use of the Site or any VeritasKWD product, program, or service.</p>
                            </li>
                        </dl>
                    </div>

                </div>

            </div>
            <FooterHeader />
        </>

    );
}
